site_name: Incidents
site_url: https://eg-etcs.github.io/incident/
theme:
  favicon: alarm.png
  logo: alarm.png
  name: material
  icon:
    annotation: material/arrow-right-circle
  features:
    # - toc.integrate
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.tracking
    - content.math
    - navigation.tabs.sticky
    
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
    
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocs-pdf
  - mkdocs-video:
      is_video: True
      video_muted: False
      is_video: True
      video_controls: True
      css_style:
        width: "100%"


nav:
  - Today's Incidents:
    - index.md
  - This Week:
    - This-Week.md
  - Last Week:
    - Last-Week.md
  - Incidents:
    - "": default.md
    - "2025" : 
      - "October": 
        - "week44": 
          - "Nihon Kohden CNS-6201": 2025/Week44/nihon-kohden-cns-6201.md
          - "ASKI Energy ALS-Mini": 2025/Week44/aski-energy-als-mini.md
          - "Delta Electronics ASDA-Soft": 2025/Week44/delta-electronics-asda-soft.md
          - "Windows Server WSUS": 2025/Week44/windows-server-wsus.md
          - "BlueNoroff Campaigns": 2025/Week44/bluenoroff-ghostcall-ghosthire.md
          - "Everest AT&T Aviation Leaks": 2025/Week44/everest-att-aviation-leaks.md
          - "HSBC USA Data Breach": 2025/Week44/hsbc-usa-data-breach.md
          - "Vertikal Hospital Manager": 2025/Week44/vertikal-hospital-manager.md
      - "November": 
         - "week45": 
            - "Cisco IOS XE": 2025/Week45/Cisco-IOS-XE.md
            - "VMware Aria Operations and VMware Tools": 2025/Week45/VMware-tools.md
            - "Android/BankBot-YNRK malware": 2025/Week45/Android-BankBot.md
            - "Cisco ASA Secure Firewall":  2025/Week45/Cisco-ASA.md
            - "Multiple Critical Vulnerabilities in Moxa": 2025/Week45/Moxa.md
            - "Super Value Co. Ransomware Breach" : 2025/Week45/Super-Value.md
            - "Android Security Bulletin": 2025/Week45/Android-Security-Bulletin.md
            - "Cyber Toufan – Maya Engineering Surveillance Breach" : 2025/Week45/maya-engineering-breach.md
         - "week46":
            - "Samsung Mobile Zero-Day Exploited to Deploy LANDFALL Spyware": 2025/Week46/samsung-spyware.md
            - "Cisco Unified Contact Center Express (Unified CCX) Vulnerabilities": 2025/Week46/cisco-ccx.md
            - "Multiple Vulnerabilities in Apple Products": 2025/Week46/apple.md
            - "ABB FLXeon Controllers Vulnerabilities": 2025/Week46/abb-fbxi.md
            - "Delhi Airport GPS Spoofing Crisis": 2025/Week46/delhi.md
            - "ClickFix Hospitality Phishing Campaign": 2025/Week46/clickfix.md
            - "Actively Exploited Windows Kernel Zero‑Day": 2025/Week46/kernel.md
            - "Whisper Leak — LLM Side‑Channel Attack": 2025/Week46/whisper.md
            - "Google vs. Lighthouse Phishing-as-a-Service Operation": 2025/Week46/Lighthouse.md
         - "week47":
            - "Fortinet FortiWeb Authentication Bypass": 2025/Week47/fortiweb.md
            - "Critical IBM AIX NIM Vulnerabilities": 2025/Week47/aix.md
            - "D‑Link DIR-816L": 2025/Week47/dlink.md
            - "Microsoft Graphics Component Vulnerability – CVE-2025-60724": 2025/Week47/ms-gfx.md
            - "Google Chrome V8 Zero-Day – CVE-2025-13223": 2025/Week47/chrome-v8.md
            - "Lynx+ Gateway Critical Vulnerabilities": 2025/Week47/lynx.md
            - "FortiWeb OS Command Injection (CVE-2025-58034)": 2025/Week47/fortiwebzero.md
         - "week48":
            - "ABB Ability Edgenius – Authentication Bypass (CVE-2025-10571)": 2025/Week48/abb.md
            - "Oracle Fusion Middleware – Missing Authentication for Critical Function (CVE-2025-61757)": 2025/Week48/oracle.md
            - "China-Linked APT31 Stealth Cyberattacks on Russian IT – Using Cloud Services": 2025/Week48/apt31.md
            - "Oracle EBS Zero-Day Exploitation – CVE-2025-61882": 2025/Week48/oracle-ebs.md
            - "CISA Warning: Spyware Campaigns Targeting Messaging App Users": 2025/Week48/spyware.md
            - "Festo Compact Vision System – Insecure Configuration Vulnerabilities": 2025/Week48/festo.md
            - "ShadowV2 IoT Botnet Opportunistic Attack During AWS Outage": 2025/Week48/shadowV2.md
         - "week49":
            - "node-forge ASN.1 Validation Bypass Vulnerability": 2025/Week49/forge.md
            - "Contagious Interview (2025 npm-registry wave)": 2025/Week49/npm.md
            - "OpenPLC ScadaBR CVE-2021-26829 Active Exploitation": 2025/Week49/openplc.md
            - "Scada-LTS Project Import Path Traversal – CVE-2025-13791": 2025/Week49/scadalts.md
            - "Mercedes-Benz USA Breach Claim by Threat Actor 'zestix'": 2025/Week49/benz.md
            - "OnSolve CodeRED Ransomware Attack": 2025/Week49/onsolve.md
            - "MuddyWater MuddyViper Backdoor Campaign": 2025/Week49/muddy.md
            - "Hacking of ~120,000 IP Cameras in South Korea for Sale of Intimate Content": 2025/Week49/knpa.md
      - "December":
         - "week50":
            - "GoldFactory Hits Southeast Asia with Modified Banking Apps Driving 11,000+ Infections": 2025/Week50/goldfactory.md
            - "WhatsApp-Based Malware Campaign by Water Saci": 2025/Week50/watersaci.md
            - "Johnson Controls FX80 / FX90 Vulnerability (CVE-2025-43867)": 2025/Week50/johnson.md
            - "React2Shell (CVE-2025-55182)": 2025/Week50/react2shell.md
            - "UDPGangster Campaigns Target Multiple Countries": 2025/Week50/muddyudp.md
            - "Android Malware Surge: FvncBot, SeedSnatcher, and Upgraded ClayRat": 2025/Week50/andSurge.md
            - "ArrayOS AG VPN (CVE-2025-66644)": 2025/Week50/arrayos.md
         - "week51":
            - "GeoServer XXE Vulnerability Exploitation (CVE-2025-58360)": 2025/Week51/geoserver.md
            - "CVE-2018-4063 Sierra Wireless AirLink ALEOS Remote Code Execution": 2025/Week51/sierra.md
            - "Pro-Russia Hacktivists Conduct Opportunistic Attacks Against Critical Infrastructure": 2025/Week51/hacktivists.md
            - "Google Chromium Out-of-Bounds Memory Access Vulnerability": 2025/Week51/chromium.md
            - "Johnson Controls iSTAR Ultra Vulnerabilities": 2025/Week51/istar.md
            - "Siemens Energy Services Security Advisory": 2025/Week51/siemensesa.md
            - "Apple Multiple Products Use-After-Free WebKit Vulnerability": 2025/Week51/useAfterFree.md
            - "Fortinet FortiCloud SSO Login Authentication Bypass Vulnerabilities": 2025/Week51/forticloud.md
            - "SolarEdge SE3680H Contains Linux Kernel Vulnerabilities": 2025/Week51/solaredge.md
            - "Russian GRU Cyber Campaign Targeting Critical Infrastructure via Edge Network Devices": 2025/Week51/RussianGRU.md
            - "OS Command Injection in Fortinet FortiSandbox": 2025/Week51/sandbox.md
            - "Cisco AsyncOS Zero-Day Exploitation Campaign": 2025/Week51/AsyncOS.md
            - "ASUS Live Update Embedded Malicious Code Vulnerability": 2025/Week51/asus.md
            - "SonicWall SMA1000 Zero-Day Vulnerabilities": 2025/Week51/sonicWall.md
         - "week52":
            - "CVE-2025-14993: Tenda AC18 Router Stack Buffer Overflow'": 2025/Week52/ac18.md
            - "WatchGuard Firebox Fireware OS IKEv2 Out-of-Bounds Write Vulnerability": 2025/Week52/watchguard.md
            - "U.S. DOJ Charges 54 in ATM Jackpotting Scheme Using Ploutus Malware" : 2025/Week52/doj.md
            - "Romanian Waters Authority Hit by Ransomware Attack": 2025/Week52/romanian.md
            - "Kimwolf Botnet: 1.8 Million Android Devices Hijacked": 2025/Week52/kimwolf.md
            - "China-Linked \"Ink Dragon\" APT Espionage Campaign": 2025/Week52/dragon.md
            - "Cyberattack on La Poste and La Banque Postale": 2025/Week52/laposte.md
            - "CVE-2025-68613: Critical n8n Remote Code Execution Vulnerability": 2025/Week52/n8n.md
            - "Lotusbail: Malicious npm Package Targeting WhatsApp Web API Developers": 2025/Week52/lotusbail.md
            - "MacSync macOS Stealer: Code-Signed Malware Bypassing Gatekeeper": 2025/Week52/macsync.md
            - "FBI Seizure of Fraud Domain Hosting Stolen Bank Credentials": 2025/Week52/fbi.md
         - "week53":
            - "Trust Wallet Chrome Extension Supply-Chain Attack": 2025/Week53/wallet.md
            - "CVE-2025-68664: Critical LangChain Core Serialization Injection Vulnerability": 2025/Week53/langchain.md
            - "GhostPairing: WhatsApp Account Takeover via Social Engineering": 2025/Week53/ghostpairing.md
            - "Fortinet FortiOS SSL VPN 2FA Bypass (CVE-2020-12812)": 2025/Week53/vpn2fa.md
            - "Digiever DS-2105 Pro NVR Authorization Bypass & Command Injection": 2025/Week53/digiever.md
            - "Malicious npm Packages Abused as Phishing Infrastructure": 2025/Week53/npm.md
            - "Critical SmarterMail Arbitrary File Upload / Remote Code Execution Vulnerability": 2025/Week53/smartermail.md
            - "MongoBleed: MongoDB Memory Disclosure (CVE-2025-14847)": 2025/Week53/mongo.md
    - "2026" : 
      - "January": 
        - "week1": 
          - "IBM API Connect Critical Authentication Bypass (CVE-2025-13915)": 2026/Week1/api_connect.md
          - "Transparent Tribe RAT Campaign Targeting Indian Government and Academia": 2026/Week1/transparent_tribe.md
          - "ClickFix Attack Uses Fake Windows BSOD to Push Malware": 2026/Week1/clickfix_BSOD.md
          - "n8n Critical Python Sandbox Bypass (CVE-2025-68668)": 2026/Week1/n8n2.md
        - "week2": 
          - "MuddyWater RustyWater RAT Campaign – Iran-linked APT Espionage": 2026/Week2/RustyWater.md
          - "Astaroth Banking Trojan – WhatsApp Worm Campaign in Brazil": 2026/Week2/Astaroth.md
          - "Instagram 17.5M User Data Leak – API Scraping Incident": 2026/Week2/Instagram.md
          - "Trend Micro Apex Central Unauthenticated RCE (CVE-2025-69258)": 2026/Week2/apex.md
          - "Kimsuky APT Malicious QR Code Spear-Phishing Campaign": 2026/Week2/Kimsuky.md
          - "APT28 Credential-Stealing Campaign Targeting Energy and Policy Organizations": 2026/Week2/APT28.md
          - "Telegram Proxy One-Click IP Exposure Vulnerability": 2026/Week2/telegram.md
          - "UAT-7290 China-Linked Telecom Espionage Campaign": 2026/Week2/uat.md
          - "AZ Monica Hospital Cyberattack - Belgium": 2026/Week2/azmonica.md
          - "CVE-2025-8110 - Gogs Remote Code Execution via Symlink Traversal": 2026/Week2/gogs.md
          - "PLUGGYAPE Malware Campaign Targeting Ukrainian Defense Forces": 2026/Week2/pluggyape.md
          - "Android Dolby Audio Zero-Click Vulnerability (CVE-2025-54957)": 2026/Week2/dolby.md
        - "week3":
          - "Critical Authentication Bypass in Modular DS WordPress Plugin (CVE-2026-23550)": 2026/Week3/wordpress.md 
          - "Credential-Stealing Chrome Extensions Target Enterprise HR Platforms": 2026/Week3/chrome.md
          - "Iran State Television Broadcast Hijacking (Badr Satellite Signal Intrusion)": 2026/Week3/stateTV.md
          - "TP-Link VIGI Camera Authentication Bypass (CVE-2026-0629)": 2026/Week3/vigi.md
          - "CrashFix: Malicious Chrome Extension Browser Crash Social Engineering Campaign": 2026/Week3/crashfix.md
          - "GootLoader Malware - Malformed ZIP Evasion Campaign": 2026/Week3/zip.md
          - "UAT-8837: China-Linked APT Targeting North American Critical Infrastructure": 2026/Week3/talos.md
          - "Oracle HTTP Server / WebLogic Server Proxy Plug-in Vulnerability (CVE-2026-21962)": 2026/Week3/weblogic.md
          - "Google Gemini Prompt Injection Flaw via Calendar Invites": 2026/Week3/gemini.md
          - "Microsoft Power Apps Remote Code Execution Vulnerability": 2026/Week3/power.md
          - "Cisco Unified Communications Products Remote Code Execution Vulnerability": 2026/Week3/cisco.md
          - "LinkedIn Phishing Malware Campaign via DLL Sideloading": 2026/Week3/linkedin.md
          - "Command Injection Vulnerability in Zoom Node Multimedia Routers (MMRs)": 2026/Week3/zoom.md
          - "Multiple GitLab Vulnerabilities Enable 2FA Bypass and DoS Attacks": 2026/Week3/gitlab.md
        - "week4":
          - "CVE-2026-24061 – GNU InetUtils telnetd Remote Authentication Bypass": 2026/Week4/gnu.md
          - "DynoWiper Cyberattack on Polish Energy Systems (Sandworm Attribution)": 2026/Week4/dynowiper.md
          - "48 Million Gmail Usernames And Passwords Leaked Online": 2026/Week4/gmail.md
          - "Xiaomi Redmi Buds Bluetooth RFCOMM Vulnerabilities": 2026/Week4/buds.md
          - "CodeBreach – AWS CodeBuild Misconfiguration Vulnerability": 2026/Week4/codebreach.md
          - "Multi-Stage Phishing Campaign Deploying Amnesia RAT and Hakuna Matata Ransomware": 2026/Week4/amnesia.md
          - "Google Protocol Buffers JSON Parsing Denial-of-Service Vulnerability": 2026/Week4/protobuf.md
          - "Microsoft Office Security Feature Bypass Vulnerability": 2026/Week4/office.md
          - "WinRAR Path Traversal Vulnerability": 2026/Week4/winrar.md
          - "Critical Grist-Core Vulnerability Allows RCE Attacks via Spreadsheet Formulas": 2026/Week4/grist.md
          - "vm2 Sandbox Escape Vulnerability": 2026/Week4/vm2.md
      - "February": 
        - "week5": 
          - "RedKitten — Iran-Linked Cyber-Espionage Campaign": 2026/Week5/redkitten.md
          - "eScan Antivirus Update Server Compromise": 2026/Week5/escan.md
          - "Clawdbot (OpenClaw) 1-Click Remote Code Execution Vulnerability": 2026/Week5/clawdbot.md
          - "Russian APT28 Exploit Zero-Day Hours After Microsoft Discloses Office Vulnerability": 2026/Week5/apt28.md
          - "GhostChat – Android Spyware Disguised as Chat/Dating Application": 2026/Week5/ghostchat.md
          - "Over 3.28 Million Fortinet Devices Exposed via FortiCloud SSO Authentication Bypass": 2026/Week5/fortinet.md
          - "Shutdown of Flock Safety ALPR System in Mountain View": 2026/Week5/flock.md
          - "CVE-2026-25049 – Critical Remote Code Execution in n8n Workflow Expressions": 2026/Week5/n8n.md
          - "CVE-2026-25202 – MagicINFO 9 Server Hardcoded Database Credentials Vulnerability": 2026/Week5/magicinfo.md
          - "Cisco Meeting Management Arbitrary File Upload Vulnerability": 2026/Week5/cisco.md
        - "week6": 
          - "SmarterMail Unauthenticated Remote Code Execution (RCE)": 2026/Week6/smartermail.md
          - "DKnife – Linux-based Adversary-in-the-Middle (AiTM) Traffic-Hijacking Toolkit": 2026/Week6/dknife.md
          - "BridgePay Network Solutions Ransomware Attack": 2026/Week6/bridgepay.md
          - "Signal Account Hijacking Campaign": 2026/Week6/signal.md
          - "Fortinet FortiClientEMS Critical SQL Injection (CVE-2026-21643)": 2026/Week6/forticlientems.md
          - "UNC3886 Cyber Espionage Campaign Against Singapore Telcos": 2026/Week6/unc3886.md
          - "Windows 11 Notepad Markdown Remote Code Execution Vulnerability": 2026/Week6/notepad.md
          - "Senegal National ID Office Ransomware Attack": 2026/Week6/senegal.md
          - "Apple Zero-Day Exploitation (CVE-2026-20700)": 2026/Week6/apple.md
          - "ZeroDayRAT Spyware Grants Attackers Total Access to Mobile Devices": 2026/Week6/zerodayrat.md
        - "week7":
          - "Russian Government Attempts to Block WhatsApp and Restrict Telegram": 2026/Week7/russian.md
          - "CVE-2026-1731 – BeyondTrust Pre-Authentication RCE Vulnerability": 2026/Week7/beyondtrust.md
          - "Google Links China, Iran, Russia, North Korea to Coordinated Defense Sector Cyber Operations": 2026/Week7/google.md
          - "Suspected Russian Hackers Deploy CANFAIL Malware Against Ukraine": 2026/Week7/canfail.md
          - "UAT-9921 Deploys VoidLink Malware to Target Technology and Financial Sectors": 2026/Week7/uat9921.md
          - "CVE-2026-1340 — Ivanti Endpoint Manager Mobile (EPMM) Pre-Auth Remote Code Execution": 2026/Week7/ivanti.md
          - "Dell RecoverPoint for Virtual Machines Zero-Day Exploitation (CVE-2026-22769)": 2026/Week7/recoverPoint.md
          - "Keenadu — An Android Firmware-Embedded Backdoor Malware": 2026/Week7/keenadu.md